# Generated by Django 6.0.4 on 2026-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('catering_option', models.CharField(choices=[('premium_14_99', '$14.99/person – Polau, Chicken Roast leg/thai, Fish Bhona, Beef Rezella, Kebab, Firni/Payes'), ('standard_10_99', '$10.99/person – Polau, Chicken Roast leg/thai, Fish Bhona, Kebab, Firni/Payes'), ('basic_7_99', '$7.99/person – Polau, Chicken Roast leg/thai, Kebab, Firni/Payes'), ('wrap_5_99', '$5.99/person – Shawarma Chicken Wrap with Naan'), ('biryani_4_99', '$4.99/person – Chicken Biryani with leg/thai and an egg')], max_length=50)),
                ('number_of_persons', models.PositiveIntegerField(default=1)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('replace_beef_mutton', models.BooleanField(default=False)),
                ('other_notes', models.TextField(blank=True)),
                ('service_method', models.CharField(choices=[('pickup', 'Pick-up (Free of charge)'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=20)),
                ('service_other', models.CharField(blank=True, max_length=200)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
